### ISSUE TITLE
Not able to send any log to Splunk using Lo4Net and Splunk libraries v1.6.1

### ISSUE THREAD

**Issue by michierus** [AlanBarber/NLog.Targets.Splunk#12]
HI Alan,

do you have another console for testing? I tried using your console app for test with no luck.
Checking the code I could not compile it, it seems that it is not using the last version of Splunk libraries because of the Send method from HttpEventCollectorSender is not accepting all parameters,

`protected override void Append(LoggingEvent loggingEvent)
        {
            // Sanity check for LogEventInfo
            if (loggingEvent == null)
            {
                throw new ArgumentNullException(nameof(loggingEvent));
            }

            // Make sure we have a properly setup HttpEventCollectorSender
            if (_hecSender == null)
            {
                throw new Exception("SplunkHttpEventCollector Append() called before ActivateOptions()");
            }

            // Build metaData
            var metaData = new HttpEventCollectorEventInfo.Metadata(null, loggingEvent.LoggerName, "_json", GetMachineName());

            // Build properties object and assign standard values
            var properties = new Dictionary<String, object>
            {
                {"Source", loggingEvent.LoggerName},
                { "Host", GetMachineName()}
            };
            

            // Get properties from event
            if (loggingEvent.Properties != null && loggingEvent.Properties.Count > 0)
            {
                foreach (var key in loggingEvent.Properties.GetKeys())
                {
                    properties.Add(key, loggingEvent.Properties[key]);
                }
            }
            
            _hecSender.Send(null, loggingEvent.Level.Name, null, loggingEvent.RenderedMessage, loggingEvent.ExceptionObject, properties, metaData);
            _hecSender.FlushSync();
        }`

I had success using as follow,
`_hecSender.Send("1", loggingEvent.Level.Name, loggingEvent.RenderedMessage);`

Thank you.

**Comment by michierus** [comment]
Hi

**Comment by AlanBarber** [comment]
The project no longer makes reference to the splunk 1.6.1 libs. Due to splunk's refusal to make changes to support NetCore I pulled their code in and embeded it.  If you pull a clean copy of the project it should compile and run just fine (I'm using VS 2017 btw).

**Comment by michierus** [comment]
Hi Alan,

thank you I found the thread, https://github.com/splunk/splunk-library-dotnetlogging/issues/24
