### ISSUE TITLE
Thousands of sockets opened under heavy load

### ISSUE THREAD

**Issue by maxiptah** [AlanBarber/NLog.Targets.Splunk#20]
Hi, I've opened an issue on Splunk here https://github.com/splunk/splunk-library-dotnetlogging/issues/52 
Do you think it may be relevant for your package? We are using your package for Splunk logging, but under heavy load (thousands of messages a minute) the app runs out of sockets.

**Comment by snakefoot** [comment]
Created #21

**Comment by snakefoot** [comment]
@AlanBarber Created #21

**Comment by AlanBarber** [comment]
@snakefoot As always thanks for all your help! I've pushed up a new version 2.2.1 

https://www.nuget.org/packages/NLog.Targets.Splunk/2.2.1

**Comment by snakefoot** [comment]
@AlanBarber Always nice to help a project with an active owner/maintainer :)
