### ISSUE TITLE
Add strong name to the assembly

### ISSUE THREAD

**Issue by raydk** [AlanBarber/NLog.Targets.Splunk#36]
Would you be able to add a strong name key file to the project? 
I am unfortunately not able to use the library in a project which has a strong name...

**Comment by VishrutPatelCitrix** [comment]
We would also like to use it, but require a strongly named assembly. Can we self sign the assembly? If not when can we expect the needful? Thank you.

**Comment by AlanBarber** [comment]
I'm going to add strong naming in the next release. closing for now.
