### ISSUE TITLE
Index, Source and SourceType Metadata

### ISSUE THREAD

**Issue by Haddox19** [AlanBarber/NLog.Targets.Splunk#37]
Can someone please commit my changes for Index, Source and SourceType metadata being defined in the nlog.config. I dont have the time to sit here and struggle with getting my changes synced into Git. These changes should be veryhelpful for anyone using Splunk through Nlog!

[SplunkHttpEventCollector.txt](https://github.com/AlanBarber/NLog.Targets.Splunk/files/3699148/SplunkHttpEventCollector.txt)

**Comment by snakefoot** [comment]
Created #38 for you.

**Comment by Haddox19** [comment]
Thank you for your assistance! I had to update my git extension in TFS. I got it working now for future updates. Just didnt have the time yesterday to mess with it.

**Comment by vikassaini80** [comment]
Hey Haddox 

I want to use this splunk.targate with source and index for my .net code, can you please help me or post me some sample code for the same,
er.vikassaini84@gmail.com
appreciate your effort.

Thanks
Vikas Saini
