### ISSUE TITLE
Change Source

### ISSUE THREAD

**Issue by gunnarstei** [AlanBarber/NLog.Targets.Splunk#39]
Source is always namespace + class name (that logged in NLog).

If you could please let users define Source in nlog.xml it would be awesome 👍 

Thanks,
Gunnar

P.S. There doesn't seem to be a way around it. Even if I create a Splunk HTTP Event Collector and put a value in "Source name override", I still get namespace + classname as source.

**Comment by snakefoot** [comment]
Will be resolved in #38 if should be merged.

**Comment by AlanBarber** [comment]
I'll get a new build out and published today.
