### ISSUE TITLE
NLog Splunk isuse for setting index and sourcetype

### ISSUE THREAD

**Issue by Rajesh-Gour** [AlanBarber/NLog.Targets.Splunk#44]
i have configured my application to target splunk and i am able to send logs to Splunk as per the configuration suggested your github repository page.
I was trying to set up SourceType and Index properties available in SplunkHttpEventCollector  class either using program logic or via configuration file but nothing seems to be working.

Could you please suggest me how we can setup these 2 properties via configuration or program logic ?

**Comment by snakefoot** [comment]
Sounds like you are waiting for an updated nuget-package that includes #38

@AlanBarber Any chance for a new build to be released?

**Comment by raulplanas** [comment]
@AlanBarber When is #38 being released in a new nuget package?

**Comment by AlanBarber** [comment]
Version 3.0 of the lib that has been published has changes for #38
