### ISSUE TITLE
Time-field format / Missing CultureInfo.InvariantCulture

### ISSUE THREAD

**Issue by sorenhjarlvig** [AlanBarber/NLog.Targets.Splunk#5]
Hi there,

When running with danish culture settings the time-field in the message for Splunk is formatted like this:

`"time":"1522836454,671", ...`
(notice comma being used as separator)

This results in Splunk rejecting the message with http code 400.
The fix is to add CultureInfo.InvariantCulture to epochTime.ToString in the HttpEventCollectorEventInfo class:

`Timestamp = epochTime.ToString("#.000", CultureInfo.InvariantCulture); // truncate to 3 digits after floating point`

Best regards

Soeren 

#7

**Comment by AlanBarber** [comment]
thanks for the report. I've added the change that will be included in the 2.0 release today
