### ISSUE TITLE
Nothing is logged if Splunk target is not available

### ISSUE THREAD

**Issue by TiQ79** [AlanBarber/NLog.Targets.Splunk#6]
I just tried out a console test app without having a valid Splunk target running.
I don't get any error message that there is not Splunk on the requested URL, only getting the console log.
Is this target fire and forget or should it actually write to the internal log if not available?

`<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="Info"
      internalLogFile="nlog-internal.log">
  <extensions>
		<add assembly="NLog.Targets.Splunk" />
	</extensions>
  <targets>
    <target name="ConsoleLogger"
            xsi:type="Console"
            layout="Console Logger: ${longdate} | ${level:uppercase=true} | ${logger} | ${message} ${exception:format=tostring}" />
    <target name="Splunk"
            xsi:type="SplunkHttpEventCollector"
            ServerUrl="https://splunkindexer.someserver.ch:8080"
            Token="3822021F-DFEC-4B20-9292-9C39F4647845"
            RetriesOnError="0"
            layout="${message} ${exception:format=tostring}" />
	</targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="ConsoleLogger" />
		<logger name="*" minLevel="Trace" writeTo="Splunk" />
	</rules>
</nlog>`

**Comment by AlanBarber** [comment]
this was a known issue with the 1.0 release. I had left in some bad code that would throw an error if it failed to connect to the splunk server. the 2.0 release which will be out today will remove that.
