### ISSUE TITLE
.Net Dependency

### ISSUE THREAD

**Issue by zhongxun** [AlanBarber/NLog.Targets.Splunk#8]
Thank you for the great job! I notice you already copied code from Splunk.Logging.Common, and updated project to .net standard. Could you also remove dependency to Splunk.Logging.Common (>= 1.6.1) which is a .Net assembly? So it would not be restored, which causes incompatibility to .net core project

**Comment by AlanBarber** [comment]
The 2.0.0 release of the package which should be uploaded sometime today will have the dependency removed.
